name: ci-cd

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_changes:
    uses: ./check-changes-action.yml@${{ github.sha }}
    with:
      file_patterns: '.*'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Building the project"

  create_check:
    needs: [check_changes, build]
    uses: ./create-check.yml@${{ github.sha }}
    with:
      code_was_changed: ${{ needs.check_changes.outputs.code_was_changed }}
      check_name: 'workflow-config-check'
      check_result: ${{ needs.build.result }}

