name: ci-cd

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check_changes:
    uses: patmoreau/renovate-config/.github/workflows/check-changes-action.yml@main
    with:
      file_patterns: '.*'
